/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessageEnumScheduleType {
    #[serde(rename = "fixed")]
    Fixed,

}

impl std::fmt::Display for MessageEnumScheduleType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Fixed => write!(f, "fixed"),
        }
    }
}

impl Default for MessageEnumScheduleType {
    fn default() -> MessageEnumScheduleType {
        Self::Fixed
    }
}

