/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentsEnumBankAccountType {
    #[serde(rename = "consumer-checking")]
    ConsumerChecking,
    #[serde(rename = "consumer-savings")]
    ConsumerSavings,
    #[serde(rename = "commercial-checking")]
    CommercialChecking,

}

impl std::fmt::Display for PaymentsEnumBankAccountType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ConsumerChecking => write!(f, "consumer-checking"),
            Self::ConsumerSavings => write!(f, "consumer-savings"),
            Self::CommercialChecking => write!(f, "commercial-checking"),
        }
    }
}

impl Default for PaymentsEnumBankAccountType {
    fn default() -> PaymentsEnumBankAccountType {
        Self::ConsumerChecking
    }
}

