/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UsageRecordEnumCategory {
    #[serde(rename = "a2p-registration-fees")]
    A2pRegistrationFees,
    #[serde(rename = "agent-conference")]
    AgentConference,
    #[serde(rename = "amazon-polly")]
    AmazonPolly,
    #[serde(rename = "answering-machine-detection")]
    AnsweringMachineDetection,
    #[serde(rename = "authy-authentications")]
    AuthyAuthentications,
    #[serde(rename = "authy-calls-outbound")]
    AuthyCallsOutbound,
    #[serde(rename = "authy-monthly-fees")]
    AuthyMonthlyFees,
    #[serde(rename = "authy-phone-intelligence")]
    AuthyPhoneIntelligence,
    #[serde(rename = "authy-phone-verifications")]
    AuthyPhoneVerifications,
    #[serde(rename = "authy-sms-outbound")]
    AuthySmsOutbound,
    #[serde(rename = "call-progess-events")]
    CallProgessEvents,
    #[serde(rename = "calleridlookups")]
    Calleridlookups,
    #[serde(rename = "calls")]
    Calls,
    #[serde(rename = "calls-client")]
    CallsClient,
    #[serde(rename = "calls-globalconference")]
    CallsGlobalconference,
    #[serde(rename = "calls-inbound")]
    CallsInbound,
    #[serde(rename = "calls-inbound-local")]
    CallsInboundLocal,
    #[serde(rename = "calls-inbound-mobile")]
    CallsInboundMobile,
    #[serde(rename = "calls-inbound-tollfree")]
    CallsInboundTollfree,
    #[serde(rename = "calls-outbound")]
    CallsOutbound,
    #[serde(rename = "calls-pay-verb-transactions")]
    CallsPayVerbTransactions,
    #[serde(rename = "calls-recordings")]
    CallsRecordings,
    #[serde(rename = "calls-sip")]
    CallsSip,
    #[serde(rename = "calls-sip-inbound")]
    CallsSipInbound,
    #[serde(rename = "calls-sip-outbound")]
    CallsSipOutbound,
    #[serde(rename = "calls-transfers")]
    CallsTransfers,
    #[serde(rename = "carrier-lookups")]
    CarrierLookups,
    #[serde(rename = "conversations")]
    Conversations,
    #[serde(rename = "conversations-api-requests")]
    ConversationsApiRequests,
    #[serde(rename = "conversations-conversation-events")]
    ConversationsConversationEvents,
    #[serde(rename = "conversations-endpoint-connectivity")]
    ConversationsEndpointConnectivity,
    #[serde(rename = "conversations-events")]
    ConversationsEvents,
    #[serde(rename = "conversations-participant-events")]
    ConversationsParticipantEvents,
    #[serde(rename = "conversations-participants")]
    ConversationsParticipants,
    #[serde(rename = "cps")]
    Cps,
    #[serde(rename = "flex-usage")]
    FlexUsage,
    #[serde(rename = "fraud-lookups")]
    FraudLookups,
    #[serde(rename = "group-rooms")]
    GroupRooms,
    #[serde(rename = "group-rooms-data-track")]
    GroupRoomsDataTrack,
    #[serde(rename = "group-rooms-encrypted-media-recorded")]
    GroupRoomsEncryptedMediaRecorded,
    #[serde(rename = "group-rooms-media-downloaded")]
    GroupRoomsMediaDownloaded,
    #[serde(rename = "group-rooms-media-recorded")]
    GroupRoomsMediaRecorded,
    #[serde(rename = "group-rooms-media-routed")]
    GroupRoomsMediaRouted,
    #[serde(rename = "group-rooms-media-stored")]
    GroupRoomsMediaStored,
    #[serde(rename = "group-rooms-participant-minutes")]
    GroupRoomsParticipantMinutes,
    #[serde(rename = "group-rooms-recorded-minutes")]
    GroupRoomsRecordedMinutes,
    #[serde(rename = "imp-v1-usage")]
    ImpV1Usage,
    #[serde(rename = "lookups")]
    Lookups,
    #[serde(rename = "marketplace")]
    Marketplace,
    #[serde(rename = "marketplace-algorithmia-named-entity-recognition")]
    MarketplaceAlgorithmiaNamedEntityRecognition,
    #[serde(rename = "marketplace-cadence-transcription")]
    MarketplaceCadenceTranscription,
    #[serde(rename = "marketplace-cadence-translation")]
    MarketplaceCadenceTranslation,
    #[serde(rename = "marketplace-capio-speech-to-text")]
    MarketplaceCapioSpeechToText,
    #[serde(rename = "marketplace-convriza-ababa")]
    MarketplaceConvrizaAbaba,
    #[serde(rename = "marketplace-deepgram-phrase-detector")]
    MarketplaceDeepgramPhraseDetector,
    #[serde(rename = "marketplace-digital-segment-business-info")]
    MarketplaceDigitalSegmentBusinessInfo,
    #[serde(rename = "marketplace-facebook-offline-conversions")]
    MarketplaceFacebookOfflineConversions,
    #[serde(rename = "marketplace-google-speech-to-text")]
    MarketplaceGoogleSpeechToText,
    #[serde(rename = "marketplace-ibm-watson-message-insights")]
    MarketplaceIbmWatsonMessageInsights,
    #[serde(rename = "marketplace-ibm-watson-message-sentiment")]
    MarketplaceIbmWatsonMessageSentiment,
    #[serde(rename = "marketplace-ibm-watson-recording-analysis")]
    MarketplaceIbmWatsonRecordingAnalysis,
    #[serde(rename = "marketplace-ibm-watson-tone-analyzer")]
    MarketplaceIbmWatsonToneAnalyzer,
    #[serde(rename = "marketplace-icehook-systems-scout")]
    MarketplaceIcehookSystemsScout,
    #[serde(rename = "marketplace-infogroup-dataaxle-bizinfo")]
    MarketplaceInfogroupDataaxleBizinfo,
    #[serde(rename = "marketplace-keen-io-contact-center-analytics")]
    MarketplaceKeenIoContactCenterAnalytics,
    #[serde(rename = "marketplace-marchex-cleancall")]
    MarketplaceMarchexCleancall,
    #[serde(rename = "marketplace-marchex-sentiment-analysis-for-sms")]
    MarketplaceMarchexSentimentAnalysisForSms,
    #[serde(rename = "marketplace-marketplace-nextcaller-social-id")]
    MarketplaceMarketplaceNextcallerSocialId,
    #[serde(rename = "marketplace-mobile-commons-opt-out-classifier")]
    MarketplaceMobileCommonsOptOutClassifier,
    #[serde(rename = "marketplace-nexiwave-voicemail-to-text")]
    MarketplaceNexiwaveVoicemailToText,
    #[serde(rename = "marketplace-nextcaller-advanced-caller-identification")]
    MarketplaceNextcallerAdvancedCallerIdentification,
    #[serde(rename = "marketplace-nomorobo-spam-score")]
    MarketplaceNomoroboSpamScore,
    #[serde(rename = "marketplace-payfone-tcpa-compliance")]
    MarketplacePayfoneTcpaCompliance,
    #[serde(rename = "marketplace-remeeting-automatic-speech-recognition")]
    MarketplaceRemeetingAutomaticSpeechRecognition,
    #[serde(rename = "marketplace-tcpa-defense-solutions-blacklist-feed")]
    MarketplaceTcpaDefenseSolutionsBlacklistFeed,
    #[serde(rename = "marketplace-telo-opencnam")]
    MarketplaceTeloOpencnam,
    #[serde(rename = "marketplace-truecnam-true-spam")]
    MarketplaceTruecnamTrueSpam,
    #[serde(rename = "marketplace-twilio-caller-name-lookup-us")]
    MarketplaceTwilioCallerNameLookupUs,
    #[serde(rename = "marketplace-twilio-carrier-information-lookup")]
    MarketplaceTwilioCarrierInformationLookup,
    #[serde(rename = "marketplace-voicebase-pci")]
    MarketplaceVoicebasePci,
    #[serde(rename = "marketplace-voicebase-transcription")]
    MarketplaceVoicebaseTranscription,
    #[serde(rename = "marketplace-voicebase-transcription-custom-vocabulary")]
    MarketplaceVoicebaseTranscriptionCustomVocabulary,
    #[serde(rename = "marketplace-whitepages-pro-caller-identification")]
    MarketplaceWhitepagesProCallerIdentification,
    #[serde(rename = "marketplace-whitepages-pro-phone-intelligence")]
    MarketplaceWhitepagesProPhoneIntelligence,
    #[serde(rename = "marketplace-whitepages-pro-phone-reputation")]
    MarketplaceWhitepagesProPhoneReputation,
    #[serde(rename = "marketplace-wolfarm-spoken-results")]
    MarketplaceWolfarmSpokenResults,
    #[serde(rename = "marketplace-wolfram-short-answer")]
    MarketplaceWolframShortAnswer,
    #[serde(rename = "marketplace-ytica-contact-center-reporting-analytics")]
    MarketplaceYticaContactCenterReportingAnalytics,
    #[serde(rename = "mediastorage")]
    Mediastorage,
    #[serde(rename = "mms")]
    Mms,
    #[serde(rename = "mms-inbound")]
    MmsInbound,
    #[serde(rename = "mms-inbound-longcode")]
    MmsInboundLongcode,
    #[serde(rename = "mms-inbound-shortcode")]
    MmsInboundShortcode,
    #[serde(rename = "mms-messages-carrierfees")]
    MmsMessagesCarrierfees,
    #[serde(rename = "mms-outbound")]
    MmsOutbound,
    #[serde(rename = "mms-outbound-longcode")]
    MmsOutboundLongcode,
    #[serde(rename = "mms-outbound-shortcode")]
    MmsOutboundShortcode,
    #[serde(rename = "monitor-reads")]
    MonitorReads,
    #[serde(rename = "monitor-storage")]
    MonitorStorage,
    #[serde(rename = "monitor-writes")]
    MonitorWrites,
    #[serde(rename = "notify")]
    Notify,
    #[serde(rename = "notify-actions-attempts")]
    NotifyActionsAttempts,
    #[serde(rename = "notify-channels")]
    NotifyChannels,
    #[serde(rename = "number-format-lookups")]
    NumberFormatLookups,
    #[serde(rename = "pchat")]
    Pchat,
    #[serde(rename = "pchat-users")]
    PchatUsers,
    #[serde(rename = "peer-to-peer-rooms-participant-minutes")]
    PeerToPeerRoomsParticipantMinutes,
    #[serde(rename = "pfax")]
    Pfax,
    #[serde(rename = "pfax-minutes")]
    PfaxMinutes,
    #[serde(rename = "pfax-minutes-inbound")]
    PfaxMinutesInbound,
    #[serde(rename = "pfax-minutes-outbound")]
    PfaxMinutesOutbound,
    #[serde(rename = "pfax-pages")]
    PfaxPages,
    #[serde(rename = "phonenumbers")]
    Phonenumbers,
    #[serde(rename = "phonenumbers-cps")]
    PhonenumbersCps,
    #[serde(rename = "phonenumbers-emergency")]
    PhonenumbersEmergency,
    #[serde(rename = "phonenumbers-local")]
    PhonenumbersLocal,
    #[serde(rename = "phonenumbers-mobile")]
    PhonenumbersMobile,
    #[serde(rename = "phonenumbers-setups")]
    PhonenumbersSetups,
    #[serde(rename = "phonenumbers-tollfree")]
    PhonenumbersTollfree,
    #[serde(rename = "premiumsupport")]
    Premiumsupport,
    #[serde(rename = "proxy")]
    Proxy,
    #[serde(rename = "proxy-active-sessions")]
    ProxyActiveSessions,
    #[serde(rename = "pstnconnectivity")]
    Pstnconnectivity,
    #[serde(rename = "pv")]
    Pv,
    #[serde(rename = "pv-composition-media-downloaded")]
    PvCompositionMediaDownloaded,
    #[serde(rename = "pv-composition-media-encrypted")]
    PvCompositionMediaEncrypted,
    #[serde(rename = "pv-composition-media-stored")]
    PvCompositionMediaStored,
    #[serde(rename = "pv-composition-minutes")]
    PvCompositionMinutes,
    #[serde(rename = "pv-recording-compositions")]
    PvRecordingCompositions,
    #[serde(rename = "pv-room-participants")]
    PvRoomParticipants,
    #[serde(rename = "pv-room-participants-au1")]
    PvRoomParticipantsAu1,
    #[serde(rename = "pv-room-participants-br1")]
    PvRoomParticipantsBr1,
    #[serde(rename = "pv-room-participants-ie1")]
    PvRoomParticipantsIe1,
    #[serde(rename = "pv-room-participants-jp1")]
    PvRoomParticipantsJp1,
    #[serde(rename = "pv-room-participants-sg1")]
    PvRoomParticipantsSg1,
    #[serde(rename = "pv-room-participants-us1")]
    PvRoomParticipantsUs1,
    #[serde(rename = "pv-room-participants-us2")]
    PvRoomParticipantsUs2,
    #[serde(rename = "pv-rooms")]
    PvRooms,
    #[serde(rename = "pv-sip-endpoint-registrations")]
    PvSipEndpointRegistrations,
    #[serde(rename = "recordings")]
    Recordings,
    #[serde(rename = "recordingstorage")]
    Recordingstorage,
    #[serde(rename = "rooms-group-bandwidth")]
    RoomsGroupBandwidth,
    #[serde(rename = "rooms-group-minutes")]
    RoomsGroupMinutes,
    #[serde(rename = "rooms-peer-to-peer-minutes")]
    RoomsPeerToPeerMinutes,
    #[serde(rename = "shortcodes")]
    Shortcodes,
    #[serde(rename = "shortcodes-customerowned")]
    ShortcodesCustomerowned,
    #[serde(rename = "shortcodes-mms-enablement")]
    ShortcodesMmsEnablement,
    #[serde(rename = "shortcodes-mps")]
    ShortcodesMps,
    #[serde(rename = "shortcodes-random")]
    ShortcodesRandom,
    #[serde(rename = "shortcodes-uk")]
    ShortcodesUk,
    #[serde(rename = "shortcodes-vanity")]
    ShortcodesVanity,
    #[serde(rename = "small-group-rooms")]
    SmallGroupRooms,
    #[serde(rename = "small-group-rooms-data-track")]
    SmallGroupRoomsDataTrack,
    #[serde(rename = "small-group-rooms-participant-minutes")]
    SmallGroupRoomsParticipantMinutes,
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "sms-inbound")]
    SmsInbound,
    #[serde(rename = "sms-inbound-longcode")]
    SmsInboundLongcode,
    #[serde(rename = "sms-inbound-shortcode")]
    SmsInboundShortcode,
    #[serde(rename = "sms-messages-carrierfees")]
    SmsMessagesCarrierfees,
    #[serde(rename = "sms-messages-features")]
    SmsMessagesFeatures,
    #[serde(rename = "sms-messages-features-senderid")]
    SmsMessagesFeaturesSenderid,
    #[serde(rename = "sms-outbound")]
    SmsOutbound,
    #[serde(rename = "sms-outbound-content-inspection")]
    SmsOutboundContentInspection,
    #[serde(rename = "sms-outbound-longcode")]
    SmsOutboundLongcode,
    #[serde(rename = "sms-outbound-shortcode")]
    SmsOutboundShortcode,
    #[serde(rename = "speech-recognition")]
    SpeechRecognition,
    #[serde(rename = "studio-engagements")]
    StudioEngagements,
    #[serde(rename = "sync")]
    Sync,
    #[serde(rename = "sync-actions")]
    SyncActions,
    #[serde(rename = "sync-endpoint-hours")]
    SyncEndpointHours,
    #[serde(rename = "sync-endpoint-hours-above-daily-cap")]
    SyncEndpointHoursAboveDailyCap,
    #[serde(rename = "taskrouter-tasks")]
    TaskrouterTasks,
    #[serde(rename = "totalprice")]
    Totalprice,
    #[serde(rename = "transcriptions")]
    Transcriptions,
    #[serde(rename = "trunking-cps")]
    TrunkingCps,
    #[serde(rename = "trunking-emergency-calls")]
    TrunkingEmergencyCalls,
    #[serde(rename = "trunking-origination")]
    TrunkingOrigination,
    #[serde(rename = "trunking-origination-local")]
    TrunkingOriginationLocal,
    #[serde(rename = "trunking-origination-mobile")]
    TrunkingOriginationMobile,
    #[serde(rename = "trunking-origination-tollfree")]
    TrunkingOriginationTollfree,
    #[serde(rename = "trunking-recordings")]
    TrunkingRecordings,
    #[serde(rename = "trunking-secure")]
    TrunkingSecure,
    #[serde(rename = "trunking-termination")]
    TrunkingTermination,
    #[serde(rename = "tts-google")]
    TtsGoogle,
    #[serde(rename = "turnmegabytes")]
    Turnmegabytes,
    #[serde(rename = "turnmegabytes-australia")]
    TurnmegabytesAustralia,
    #[serde(rename = "turnmegabytes-brasil")]
    TurnmegabytesBrasil,
    #[serde(rename = "turnmegabytes-germany")]
    TurnmegabytesGermany,
    #[serde(rename = "turnmegabytes-india")]
    TurnmegabytesIndia,
    #[serde(rename = "turnmegabytes-ireland")]
    TurnmegabytesIreland,
    #[serde(rename = "turnmegabytes-japan")]
    TurnmegabytesJapan,
    #[serde(rename = "turnmegabytes-singapore")]
    TurnmegabytesSingapore,
    #[serde(rename = "turnmegabytes-useast")]
    TurnmegabytesUseast,
    #[serde(rename = "turnmegabytes-uswest")]
    TurnmegabytesUswest,
    #[serde(rename = "twilio-interconnect")]
    TwilioInterconnect,
    #[serde(rename = "verify-push")]
    VerifyPush,
    #[serde(rename = "verify-totp")]
    VerifyTotp,
    #[serde(rename = "verify-whatsapp-conversations-business-initiated")]
    VerifyWhatsappConversationsBusinessInitiated,
    #[serde(rename = "video-recordings")]
    VideoRecordings,
    #[serde(rename = "virtual-agent")]
    VirtualAgent,
    #[serde(rename = "voice-insights")]
    VoiceInsights,
    #[serde(rename = "voice-insights-client-insights-on-demand-minute")]
    VoiceInsightsClientInsightsOnDemandMinute,
    #[serde(rename = "voice-insights-ptsn-insights-on-demand-minute")]
    VoiceInsightsPtsnInsightsOnDemandMinute,
    #[serde(rename = "voice-insights-sip-interface-insights-on-demand-minute")]
    VoiceInsightsSipInterfaceInsightsOnDemandMinute,
    #[serde(rename = "voice-insights-sip-trunking-insights-on-demand-minute")]
    VoiceInsightsSipTrunkingInsightsOnDemandMinute,
    #[serde(rename = "voice-intelligence")]
    VoiceIntelligence,
    #[serde(rename = "voice-intelligence-transcription")]
    VoiceIntelligenceTranscription,
    #[serde(rename = "voice-intelligence-operators")]
    VoiceIntelligenceOperators,
    #[serde(rename = "wireless")]
    Wireless,
    #[serde(rename = "wireless-orders")]
    WirelessOrders,
    #[serde(rename = "wireless-orders-artwork")]
    WirelessOrdersArtwork,
    #[serde(rename = "wireless-orders-bulk")]
    WirelessOrdersBulk,
    #[serde(rename = "wireless-orders-esim")]
    WirelessOrdersEsim,
    #[serde(rename = "wireless-orders-starter")]
    WirelessOrdersStarter,
    #[serde(rename = "wireless-usage")]
    WirelessUsage,
    #[serde(rename = "wireless-usage-commands")]
    WirelessUsageCommands,
    #[serde(rename = "wireless-usage-commands-africa")]
    WirelessUsageCommandsAfrica,
    #[serde(rename = "wireless-usage-commands-asia")]
    WirelessUsageCommandsAsia,
    #[serde(rename = "wireless-usage-commands-centralandsouthamerica")]
    WirelessUsageCommandsCentralandsouthamerica,
    #[serde(rename = "wireless-usage-commands-europe")]
    WirelessUsageCommandsEurope,
    #[serde(rename = "wireless-usage-commands-home")]
    WirelessUsageCommandsHome,
    #[serde(rename = "wireless-usage-commands-northamerica")]
    WirelessUsageCommandsNorthamerica,
    #[serde(rename = "wireless-usage-commands-oceania")]
    WirelessUsageCommandsOceania,
    #[serde(rename = "wireless-usage-commands-roaming")]
    WirelessUsageCommandsRoaming,
    #[serde(rename = "wireless-usage-data")]
    WirelessUsageData,
    #[serde(rename = "wireless-usage-data-africa")]
    WirelessUsageDataAfrica,
    #[serde(rename = "wireless-usage-data-asia")]
    WirelessUsageDataAsia,
    #[serde(rename = "wireless-usage-data-centralandsouthamerica")]
    WirelessUsageDataCentralandsouthamerica,
    #[serde(rename = "wireless-usage-data-custom-additionalmb")]
    WirelessUsageDataCustomAdditionalmb,
    #[serde(rename = "wireless-usage-data-custom-first5mb")]
    WirelessUsageDataCustomFirst5mb,
    #[serde(rename = "wireless-usage-data-domestic-roaming")]
    WirelessUsageDataDomesticRoaming,
    #[serde(rename = "wireless-usage-data-europe")]
    WirelessUsageDataEurope,
    #[serde(rename = "wireless-usage-data-individual-additionalgb")]
    WirelessUsageDataIndividualAdditionalgb,
    #[serde(rename = "wireless-usage-data-individual-firstgb")]
    WirelessUsageDataIndividualFirstgb,
    #[serde(rename = "wireless-usage-data-international-roaming-canada")]
    WirelessUsageDataInternationalRoamingCanada,
    #[serde(rename = "wireless-usage-data-international-roaming-india")]
    WirelessUsageDataInternationalRoamingIndia,
    #[serde(rename = "wireless-usage-data-international-roaming-mexico")]
    WirelessUsageDataInternationalRoamingMexico,
    #[serde(rename = "wireless-usage-data-northamerica")]
    WirelessUsageDataNorthamerica,
    #[serde(rename = "wireless-usage-data-oceania")]
    WirelessUsageDataOceania,
    #[serde(rename = "wireless-usage-data-pooled")]
    WirelessUsageDataPooled,
    #[serde(rename = "wireless-usage-data-pooled-downlink")]
    WirelessUsageDataPooledDownlink,
    #[serde(rename = "wireless-usage-data-pooled-uplink")]
    WirelessUsageDataPooledUplink,
    #[serde(rename = "wireless-usage-mrc")]
    WirelessUsageMrc,
    #[serde(rename = "wireless-usage-mrc-custom")]
    WirelessUsageMrcCustom,
    #[serde(rename = "wireless-usage-mrc-individual")]
    WirelessUsageMrcIndividual,
    #[serde(rename = "wireless-usage-mrc-pooled")]
    WirelessUsageMrcPooled,
    #[serde(rename = "wireless-usage-mrc-suspended")]
    WirelessUsageMrcSuspended,
    #[serde(rename = "wireless-usage-sms")]
    WirelessUsageSms,
    #[serde(rename = "wireless-usage-voice")]
    WirelessUsageVoice,

}

impl std::fmt::Display for UsageRecordEnumCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::A2pRegistrationFees => write!(f, "a2p-registration-fees"),
            Self::AgentConference => write!(f, "agent-conference"),
            Self::AmazonPolly => write!(f, "amazon-polly"),
            Self::AnsweringMachineDetection => write!(f, "answering-machine-detection"),
            Self::AuthyAuthentications => write!(f, "authy-authentications"),
            Self::AuthyCallsOutbound => write!(f, "authy-calls-outbound"),
            Self::AuthyMonthlyFees => write!(f, "authy-monthly-fees"),
            Self::AuthyPhoneIntelligence => write!(f, "authy-phone-intelligence"),
            Self::AuthyPhoneVerifications => write!(f, "authy-phone-verifications"),
            Self::AuthySmsOutbound => write!(f, "authy-sms-outbound"),
            Self::CallProgessEvents => write!(f, "call-progess-events"),
            Self::Calleridlookups => write!(f, "calleridlookups"),
            Self::Calls => write!(f, "calls"),
            Self::CallsClient => write!(f, "calls-client"),
            Self::CallsGlobalconference => write!(f, "calls-globalconference"),
            Self::CallsInbound => write!(f, "calls-inbound"),
            Self::CallsInboundLocal => write!(f, "calls-inbound-local"),
            Self::CallsInboundMobile => write!(f, "calls-inbound-mobile"),
            Self::CallsInboundTollfree => write!(f, "calls-inbound-tollfree"),
            Self::CallsOutbound => write!(f, "calls-outbound"),
            Self::CallsPayVerbTransactions => write!(f, "calls-pay-verb-transactions"),
            Self::CallsRecordings => write!(f, "calls-recordings"),
            Self::CallsSip => write!(f, "calls-sip"),
            Self::CallsSipInbound => write!(f, "calls-sip-inbound"),
            Self::CallsSipOutbound => write!(f, "calls-sip-outbound"),
            Self::CallsTransfers => write!(f, "calls-transfers"),
            Self::CarrierLookups => write!(f, "carrier-lookups"),
            Self::Conversations => write!(f, "conversations"),
            Self::ConversationsApiRequests => write!(f, "conversations-api-requests"),
            Self::ConversationsConversationEvents => write!(f, "conversations-conversation-events"),
            Self::ConversationsEndpointConnectivity => write!(f, "conversations-endpoint-connectivity"),
            Self::ConversationsEvents => write!(f, "conversations-events"),
            Self::ConversationsParticipantEvents => write!(f, "conversations-participant-events"),
            Self::ConversationsParticipants => write!(f, "conversations-participants"),
            Self::Cps => write!(f, "cps"),
            Self::FlexUsage => write!(f, "flex-usage"),
            Self::FraudLookups => write!(f, "fraud-lookups"),
            Self::GroupRooms => write!(f, "group-rooms"),
            Self::GroupRoomsDataTrack => write!(f, "group-rooms-data-track"),
            Self::GroupRoomsEncryptedMediaRecorded => write!(f, "group-rooms-encrypted-media-recorded"),
            Self::GroupRoomsMediaDownloaded => write!(f, "group-rooms-media-downloaded"),
            Self::GroupRoomsMediaRecorded => write!(f, "group-rooms-media-recorded"),
            Self::GroupRoomsMediaRouted => write!(f, "group-rooms-media-routed"),
            Self::GroupRoomsMediaStored => write!(f, "group-rooms-media-stored"),
            Self::GroupRoomsParticipantMinutes => write!(f, "group-rooms-participant-minutes"),
            Self::GroupRoomsRecordedMinutes => write!(f, "group-rooms-recorded-minutes"),
            Self::ImpV1Usage => write!(f, "imp-v1-usage"),
            Self::Lookups => write!(f, "lookups"),
            Self::Marketplace => write!(f, "marketplace"),
            Self::MarketplaceAlgorithmiaNamedEntityRecognition => write!(f, "marketplace-algorithmia-named-entity-recognition"),
            Self::MarketplaceCadenceTranscription => write!(f, "marketplace-cadence-transcription"),
            Self::MarketplaceCadenceTranslation => write!(f, "marketplace-cadence-translation"),
            Self::MarketplaceCapioSpeechToText => write!(f, "marketplace-capio-speech-to-text"),
            Self::MarketplaceConvrizaAbaba => write!(f, "marketplace-convriza-ababa"),
            Self::MarketplaceDeepgramPhraseDetector => write!(f, "marketplace-deepgram-phrase-detector"),
            Self::MarketplaceDigitalSegmentBusinessInfo => write!(f, "marketplace-digital-segment-business-info"),
            Self::MarketplaceFacebookOfflineConversions => write!(f, "marketplace-facebook-offline-conversions"),
            Self::MarketplaceGoogleSpeechToText => write!(f, "marketplace-google-speech-to-text"),
            Self::MarketplaceIbmWatsonMessageInsights => write!(f, "marketplace-ibm-watson-message-insights"),
            Self::MarketplaceIbmWatsonMessageSentiment => write!(f, "marketplace-ibm-watson-message-sentiment"),
            Self::MarketplaceIbmWatsonRecordingAnalysis => write!(f, "marketplace-ibm-watson-recording-analysis"),
            Self::MarketplaceIbmWatsonToneAnalyzer => write!(f, "marketplace-ibm-watson-tone-analyzer"),
            Self::MarketplaceIcehookSystemsScout => write!(f, "marketplace-icehook-systems-scout"),
            Self::MarketplaceInfogroupDataaxleBizinfo => write!(f, "marketplace-infogroup-dataaxle-bizinfo"),
            Self::MarketplaceKeenIoContactCenterAnalytics => write!(f, "marketplace-keen-io-contact-center-analytics"),
            Self::MarketplaceMarchexCleancall => write!(f, "marketplace-marchex-cleancall"),
            Self::MarketplaceMarchexSentimentAnalysisForSms => write!(f, "marketplace-marchex-sentiment-analysis-for-sms"),
            Self::MarketplaceMarketplaceNextcallerSocialId => write!(f, "marketplace-marketplace-nextcaller-social-id"),
            Self::MarketplaceMobileCommonsOptOutClassifier => write!(f, "marketplace-mobile-commons-opt-out-classifier"),
            Self::MarketplaceNexiwaveVoicemailToText => write!(f, "marketplace-nexiwave-voicemail-to-text"),
            Self::MarketplaceNextcallerAdvancedCallerIdentification => write!(f, "marketplace-nextcaller-advanced-caller-identification"),
            Self::MarketplaceNomoroboSpamScore => write!(f, "marketplace-nomorobo-spam-score"),
            Self::MarketplacePayfoneTcpaCompliance => write!(f, "marketplace-payfone-tcpa-compliance"),
            Self::MarketplaceRemeetingAutomaticSpeechRecognition => write!(f, "marketplace-remeeting-automatic-speech-recognition"),
            Self::MarketplaceTcpaDefenseSolutionsBlacklistFeed => write!(f, "marketplace-tcpa-defense-solutions-blacklist-feed"),
            Self::MarketplaceTeloOpencnam => write!(f, "marketplace-telo-opencnam"),
            Self::MarketplaceTruecnamTrueSpam => write!(f, "marketplace-truecnam-true-spam"),
            Self::MarketplaceTwilioCallerNameLookupUs => write!(f, "marketplace-twilio-caller-name-lookup-us"),
            Self::MarketplaceTwilioCarrierInformationLookup => write!(f, "marketplace-twilio-carrier-information-lookup"),
            Self::MarketplaceVoicebasePci => write!(f, "marketplace-voicebase-pci"),
            Self::MarketplaceVoicebaseTranscription => write!(f, "marketplace-voicebase-transcription"),
            Self::MarketplaceVoicebaseTranscriptionCustomVocabulary => write!(f, "marketplace-voicebase-transcription-custom-vocabulary"),
            Self::MarketplaceWhitepagesProCallerIdentification => write!(f, "marketplace-whitepages-pro-caller-identification"),
            Self::MarketplaceWhitepagesProPhoneIntelligence => write!(f, "marketplace-whitepages-pro-phone-intelligence"),
            Self::MarketplaceWhitepagesProPhoneReputation => write!(f, "marketplace-whitepages-pro-phone-reputation"),
            Self::MarketplaceWolfarmSpokenResults => write!(f, "marketplace-wolfarm-spoken-results"),
            Self::MarketplaceWolframShortAnswer => write!(f, "marketplace-wolfram-short-answer"),
            Self::MarketplaceYticaContactCenterReportingAnalytics => write!(f, "marketplace-ytica-contact-center-reporting-analytics"),
            Self::Mediastorage => write!(f, "mediastorage"),
            Self::Mms => write!(f, "mms"),
            Self::MmsInbound => write!(f, "mms-inbound"),
            Self::MmsInboundLongcode => write!(f, "mms-inbound-longcode"),
            Self::MmsInboundShortcode => write!(f, "mms-inbound-shortcode"),
            Self::MmsMessagesCarrierfees => write!(f, "mms-messages-carrierfees"),
            Self::MmsOutbound => write!(f, "mms-outbound"),
            Self::MmsOutboundLongcode => write!(f, "mms-outbound-longcode"),
            Self::MmsOutboundShortcode => write!(f, "mms-outbound-shortcode"),
            Self::MonitorReads => write!(f, "monitor-reads"),
            Self::MonitorStorage => write!(f, "monitor-storage"),
            Self::MonitorWrites => write!(f, "monitor-writes"),
            Self::Notify => write!(f, "notify"),
            Self::NotifyActionsAttempts => write!(f, "notify-actions-attempts"),
            Self::NotifyChannels => write!(f, "notify-channels"),
            Self::NumberFormatLookups => write!(f, "number-format-lookups"),
            Self::Pchat => write!(f, "pchat"),
            Self::PchatUsers => write!(f, "pchat-users"),
            Self::PeerToPeerRoomsParticipantMinutes => write!(f, "peer-to-peer-rooms-participant-minutes"),
            Self::Pfax => write!(f, "pfax"),
            Self::PfaxMinutes => write!(f, "pfax-minutes"),
            Self::PfaxMinutesInbound => write!(f, "pfax-minutes-inbound"),
            Self::PfaxMinutesOutbound => write!(f, "pfax-minutes-outbound"),
            Self::PfaxPages => write!(f, "pfax-pages"),
            Self::Phonenumbers => write!(f, "phonenumbers"),
            Self::PhonenumbersCps => write!(f, "phonenumbers-cps"),
            Self::PhonenumbersEmergency => write!(f, "phonenumbers-emergency"),
            Self::PhonenumbersLocal => write!(f, "phonenumbers-local"),
            Self::PhonenumbersMobile => write!(f, "phonenumbers-mobile"),
            Self::PhonenumbersSetups => write!(f, "phonenumbers-setups"),
            Self::PhonenumbersTollfree => write!(f, "phonenumbers-tollfree"),
            Self::Premiumsupport => write!(f, "premiumsupport"),
            Self::Proxy => write!(f, "proxy"),
            Self::ProxyActiveSessions => write!(f, "proxy-active-sessions"),
            Self::Pstnconnectivity => write!(f, "pstnconnectivity"),
            Self::Pv => write!(f, "pv"),
            Self::PvCompositionMediaDownloaded => write!(f, "pv-composition-media-downloaded"),
            Self::PvCompositionMediaEncrypted => write!(f, "pv-composition-media-encrypted"),
            Self::PvCompositionMediaStored => write!(f, "pv-composition-media-stored"),
            Self::PvCompositionMinutes => write!(f, "pv-composition-minutes"),
            Self::PvRecordingCompositions => write!(f, "pv-recording-compositions"),
            Self::PvRoomParticipants => write!(f, "pv-room-participants"),
            Self::PvRoomParticipantsAu1 => write!(f, "pv-room-participants-au1"),
            Self::PvRoomParticipantsBr1 => write!(f, "pv-room-participants-br1"),
            Self::PvRoomParticipantsIe1 => write!(f, "pv-room-participants-ie1"),
            Self::PvRoomParticipantsJp1 => write!(f, "pv-room-participants-jp1"),
            Self::PvRoomParticipantsSg1 => write!(f, "pv-room-participants-sg1"),
            Self::PvRoomParticipantsUs1 => write!(f, "pv-room-participants-us1"),
            Self::PvRoomParticipantsUs2 => write!(f, "pv-room-participants-us2"),
            Self::PvRooms => write!(f, "pv-rooms"),
            Self::PvSipEndpointRegistrations => write!(f, "pv-sip-endpoint-registrations"),
            Self::Recordings => write!(f, "recordings"),
            Self::Recordingstorage => write!(f, "recordingstorage"),
            Self::RoomsGroupBandwidth => write!(f, "rooms-group-bandwidth"),
            Self::RoomsGroupMinutes => write!(f, "rooms-group-minutes"),
            Self::RoomsPeerToPeerMinutes => write!(f, "rooms-peer-to-peer-minutes"),
            Self::Shortcodes => write!(f, "shortcodes"),
            Self::ShortcodesCustomerowned => write!(f, "shortcodes-customerowned"),
            Self::ShortcodesMmsEnablement => write!(f, "shortcodes-mms-enablement"),
            Self::ShortcodesMps => write!(f, "shortcodes-mps"),
            Self::ShortcodesRandom => write!(f, "shortcodes-random"),
            Self::ShortcodesUk => write!(f, "shortcodes-uk"),
            Self::ShortcodesVanity => write!(f, "shortcodes-vanity"),
            Self::SmallGroupRooms => write!(f, "small-group-rooms"),
            Self::SmallGroupRoomsDataTrack => write!(f, "small-group-rooms-data-track"),
            Self::SmallGroupRoomsParticipantMinutes => write!(f, "small-group-rooms-participant-minutes"),
            Self::Sms => write!(f, "sms"),
            Self::SmsInbound => write!(f, "sms-inbound"),
            Self::SmsInboundLongcode => write!(f, "sms-inbound-longcode"),
            Self::SmsInboundShortcode => write!(f, "sms-inbound-shortcode"),
            Self::SmsMessagesCarrierfees => write!(f, "sms-messages-carrierfees"),
            Self::SmsMessagesFeatures => write!(f, "sms-messages-features"),
            Self::SmsMessagesFeaturesSenderid => write!(f, "sms-messages-features-senderid"),
            Self::SmsOutbound => write!(f, "sms-outbound"),
            Self::SmsOutboundContentInspection => write!(f, "sms-outbound-content-inspection"),
            Self::SmsOutboundLongcode => write!(f, "sms-outbound-longcode"),
            Self::SmsOutboundShortcode => write!(f, "sms-outbound-shortcode"),
            Self::SpeechRecognition => write!(f, "speech-recognition"),
            Self::StudioEngagements => write!(f, "studio-engagements"),
            Self::Sync => write!(f, "sync"),
            Self::SyncActions => write!(f, "sync-actions"),
            Self::SyncEndpointHours => write!(f, "sync-endpoint-hours"),
            Self::SyncEndpointHoursAboveDailyCap => write!(f, "sync-endpoint-hours-above-daily-cap"),
            Self::TaskrouterTasks => write!(f, "taskrouter-tasks"),
            Self::Totalprice => write!(f, "totalprice"),
            Self::Transcriptions => write!(f, "transcriptions"),
            Self::TrunkingCps => write!(f, "trunking-cps"),
            Self::TrunkingEmergencyCalls => write!(f, "trunking-emergency-calls"),
            Self::TrunkingOrigination => write!(f, "trunking-origination"),
            Self::TrunkingOriginationLocal => write!(f, "trunking-origination-local"),
            Self::TrunkingOriginationMobile => write!(f, "trunking-origination-mobile"),
            Self::TrunkingOriginationTollfree => write!(f, "trunking-origination-tollfree"),
            Self::TrunkingRecordings => write!(f, "trunking-recordings"),
            Self::TrunkingSecure => write!(f, "trunking-secure"),
            Self::TrunkingTermination => write!(f, "trunking-termination"),
            Self::TtsGoogle => write!(f, "tts-google"),
            Self::Turnmegabytes => write!(f, "turnmegabytes"),
            Self::TurnmegabytesAustralia => write!(f, "turnmegabytes-australia"),
            Self::TurnmegabytesBrasil => write!(f, "turnmegabytes-brasil"),
            Self::TurnmegabytesGermany => write!(f, "turnmegabytes-germany"),
            Self::TurnmegabytesIndia => write!(f, "turnmegabytes-india"),
            Self::TurnmegabytesIreland => write!(f, "turnmegabytes-ireland"),
            Self::TurnmegabytesJapan => write!(f, "turnmegabytes-japan"),
            Self::TurnmegabytesSingapore => write!(f, "turnmegabytes-singapore"),
            Self::TurnmegabytesUseast => write!(f, "turnmegabytes-useast"),
            Self::TurnmegabytesUswest => write!(f, "turnmegabytes-uswest"),
            Self::TwilioInterconnect => write!(f, "twilio-interconnect"),
            Self::VerifyPush => write!(f, "verify-push"),
            Self::VerifyTotp => write!(f, "verify-totp"),
            Self::VerifyWhatsappConversationsBusinessInitiated => write!(f, "verify-whatsapp-conversations-business-initiated"),
            Self::VideoRecordings => write!(f, "video-recordings"),
            Self::VirtualAgent => write!(f, "virtual-agent"),
            Self::VoiceInsights => write!(f, "voice-insights"),
            Self::VoiceInsightsClientInsightsOnDemandMinute => write!(f, "voice-insights-client-insights-on-demand-minute"),
            Self::VoiceInsightsPtsnInsightsOnDemandMinute => write!(f, "voice-insights-ptsn-insights-on-demand-minute"),
            Self::VoiceInsightsSipInterfaceInsightsOnDemandMinute => write!(f, "voice-insights-sip-interface-insights-on-demand-minute"),
            Self::VoiceInsightsSipTrunkingInsightsOnDemandMinute => write!(f, "voice-insights-sip-trunking-insights-on-demand-minute"),
            Self::VoiceIntelligence => write!(f, "voice-intelligence"),
            Self::VoiceIntelligenceTranscription => write!(f, "voice-intelligence-transcription"),
            Self::VoiceIntelligenceOperators => write!(f, "voice-intelligence-operators"),
            Self::Wireless => write!(f, "wireless"),
            Self::WirelessOrders => write!(f, "wireless-orders"),
            Self::WirelessOrdersArtwork => write!(f, "wireless-orders-artwork"),
            Self::WirelessOrdersBulk => write!(f, "wireless-orders-bulk"),
            Self::WirelessOrdersEsim => write!(f, "wireless-orders-esim"),
            Self::WirelessOrdersStarter => write!(f, "wireless-orders-starter"),
            Self::WirelessUsage => write!(f, "wireless-usage"),
            Self::WirelessUsageCommands => write!(f, "wireless-usage-commands"),
            Self::WirelessUsageCommandsAfrica => write!(f, "wireless-usage-commands-africa"),
            Self::WirelessUsageCommandsAsia => write!(f, "wireless-usage-commands-asia"),
            Self::WirelessUsageCommandsCentralandsouthamerica => write!(f, "wireless-usage-commands-centralandsouthamerica"),
            Self::WirelessUsageCommandsEurope => write!(f, "wireless-usage-commands-europe"),
            Self::WirelessUsageCommandsHome => write!(f, "wireless-usage-commands-home"),
            Self::WirelessUsageCommandsNorthamerica => write!(f, "wireless-usage-commands-northamerica"),
            Self::WirelessUsageCommandsOceania => write!(f, "wireless-usage-commands-oceania"),
            Self::WirelessUsageCommandsRoaming => write!(f, "wireless-usage-commands-roaming"),
            Self::WirelessUsageData => write!(f, "wireless-usage-data"),
            Self::WirelessUsageDataAfrica => write!(f, "wireless-usage-data-africa"),
            Self::WirelessUsageDataAsia => write!(f, "wireless-usage-data-asia"),
            Self::WirelessUsageDataCentralandsouthamerica => write!(f, "wireless-usage-data-centralandsouthamerica"),
            Self::WirelessUsageDataCustomAdditionalmb => write!(f, "wireless-usage-data-custom-additionalmb"),
            Self::WirelessUsageDataCustomFirst5mb => write!(f, "wireless-usage-data-custom-first5mb"),
            Self::WirelessUsageDataDomesticRoaming => write!(f, "wireless-usage-data-domestic-roaming"),
            Self::WirelessUsageDataEurope => write!(f, "wireless-usage-data-europe"),
            Self::WirelessUsageDataIndividualAdditionalgb => write!(f, "wireless-usage-data-individual-additionalgb"),
            Self::WirelessUsageDataIndividualFirstgb => write!(f, "wireless-usage-data-individual-firstgb"),
            Self::WirelessUsageDataInternationalRoamingCanada => write!(f, "wireless-usage-data-international-roaming-canada"),
            Self::WirelessUsageDataInternationalRoamingIndia => write!(f, "wireless-usage-data-international-roaming-india"),
            Self::WirelessUsageDataInternationalRoamingMexico => write!(f, "wireless-usage-data-international-roaming-mexico"),
            Self::WirelessUsageDataNorthamerica => write!(f, "wireless-usage-data-northamerica"),
            Self::WirelessUsageDataOceania => write!(f, "wireless-usage-data-oceania"),
            Self::WirelessUsageDataPooled => write!(f, "wireless-usage-data-pooled"),
            Self::WirelessUsageDataPooledDownlink => write!(f, "wireless-usage-data-pooled-downlink"),
            Self::WirelessUsageDataPooledUplink => write!(f, "wireless-usage-data-pooled-uplink"),
            Self::WirelessUsageMrc => write!(f, "wireless-usage-mrc"),
            Self::WirelessUsageMrcCustom => write!(f, "wireless-usage-mrc-custom"),
            Self::WirelessUsageMrcIndividual => write!(f, "wireless-usage-mrc-individual"),
            Self::WirelessUsageMrcPooled => write!(f, "wireless-usage-mrc-pooled"),
            Self::WirelessUsageMrcSuspended => write!(f, "wireless-usage-mrc-suspended"),
            Self::WirelessUsageSms => write!(f, "wireless-usage-sms"),
            Self::WirelessUsageVoice => write!(f, "wireless-usage-voice"),
        }
    }
}

impl Default for UsageRecordEnumCategory {
    fn default() -> UsageRecordEnumCategory {
        Self::A2pRegistrationFees
    }
}

